---
title: "Class05: R Graphics"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Class 5
# Data visualization and graphics in R 


```{r}
plot(1:5, col="blue", typ="o")
```

# Section 2A.
# Read the data file "weight_chart.txt" 

```{r}
baby <- read.table("bimm143_05_rstats/weight_chart.txt", header=TRUE)

plot(baby$Age, baby$Weight, typ="o", col="blue", pch=15, cex=1.5, lwd=2, ylim=c(2,10), 
     xlab="Age(months)", ylab="Weight(kg)", main="Baby weight with age")
plot(1:5, pch=1:5, cex=1:5, col=1:5)
```



# Section 2B.
## Read a new file of mouse genome features 

```{r}
mouse <- read.table("bimm143_05_rstats/feature_counts.txt", header=TRUE, sep="\t")

dotchart(mouse$Count, labels=mouse$Feature)

barplot(mouse$Count, names.arg=mouse$Feature, horiz = TRUE, ylab="", main="Number of Features in the mouse GRCm38 genome", las=1, xlim=c(0,80000))

old.par <- par()$mar
par(mar=c(3.1, 11.1, 4.1, 2))
```



# Section 3A.

```{r}
mf <- read.delim("bimm143_05_rstats/male_female_counts.txt")

barplot(mf$Count, names.arg=mf$Sample, col=rainbow( nrow(mf) ) )
```